### ISSUE TITLE
Plusin doesn't work after site's update

### ISSUE THREAD

**Issue by lonsdaleite** [Buksa/movian-plugin-HDSerials#1]
I opened the plugin today, and it doesn't work. It needs to update.

**Comment by Buksa** [comment]
What version you use?

**Comment by Buksa** [comment]
done

**Comment by lonsdaleite** [comment]
Doesn't work

Не работает
8 дек. 2015 г. 9:18 AM пользователь "Buksa" notifications@github.com
написал:

**Comment by Buksa** [comment]
обновляй до 0.11.7

**Comment by lonsdaleite** [comment]
Обновил бы, но он пропал из списка доступных плагинов
9 дек. 2015 г. 8:24 PM пользователь "Buksa" notifications@github.com
написал:

**Comment by Buksa** [comment]
узай бета пасс buksa

2015-12-09 9:43 GMT-08:00 lonsdaleite notifications@github.com:
